export const MOVIES = [
  {
    id: "1",
    title: "The Flash",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eOAWLYnOxEGFrIAMR5DeGDGNiuj.jpg",
    category: ["Action", "Adventure", "Science Fiction"],
    duration: { hr: 2, min: 24 },
    date: "06/15/2023",
    description:
      "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
    trailer: "jprhe-cWKGs",
    cast: [
      "Ezra Miller",
      "Sasha Calle",
      "Ben Affleck",
      "Gal Gadot",
      "Michael Keaton",
      "Michael Shannon",
      "Ron Livingston",
      "Maribel Verdú",
      "Kiersey Clemons",
      "Antje Traue",
    ],
    rating: 4.1,
  },

  {
    id: "2",
    title: "Oppenheimer",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2y48XTa483LRFIb5fDKOwr8DHWz.jpg",
    category: ["Drama", "History"],
    duration: { hr: 3, min: 1 },
    date: "07/21/2023",
    description:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    trailer: "sOsIKu2VAkM",
    cast: [
      "Cillian Murphy",
      "Emily Blunt",
      "Matt Damon",
      "Robert Downey Jr.",
      "Florence Pugh",
      "Benny Safdie",
      "Rami Malek",
      "Michael Angarano",
      "Josh Hartnett",
    ],
    rating: 4.8,
  },

  {
    id: "3",
    title: "Transformers: Rise of the Beasts",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/byNWRiY7Wtv8XhqpK95GxqX8ZYk.jpg",
    category: ["Action", "Adventure", "Science Fiction"],
    duration: { hr: 2, min: 7 },
    date: "06/09/2023",
    description:
      "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
    trailer: "ZtuFgnxQMrA",
    cast: [
      "Anthony Ramos",
      "Dominique Fishback",
      "Peter Cullen",
      "Ron Perlman",
      "Peter Dinklage",
      "Michelle Yeoh",
      "Pete Davidson",
      "Liza Koshy",
      "Cristo Fernández",
    ],
    rating: 3.6,
  },

  {
    id: "4",
    title: "Mission: Impossible - Dead Reckoning Part One",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zQdovqomlgXNgcLKNNl8yBL8Y4q.jpg",
    category: ["Action", "Thriller", "Adventure"],
    duration: { hr: 2, min: 44 },
    date: "07/12/2023",
    description:
      "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
    trailer: "HurjfO_TDlQ",
    cast: [
      "Tom Cruise",
      "Hayley Atwell",
      "Ving Rhames",
      "Simon Pegg",
      "Rebecca Ferguson",
      "Vanessa Kirby",
      "Esai Morales",
      "Pom Klementieff",
      "Henry Czerny",
    ],
    rating: 4.5,
  },

  {
    id: "5",
    title: "Guardians of the Galaxy Vol. 3",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/whfoSVaiR3TT7D2RDL8lfeL9I1a.jpg",
    category: ["Science Fiction", "Adventure", "Action"],
    duration: { hr: 2, min: 30 },
    date: "05/05/2023",
    description:
      "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    trailer: "AAE5VZktooM",
    cast: [
      "Chris Pratt",
      "Zoe Saldaña",
      "Dave Bautista",
      "Karen Gillan",
      "Pom Klementieff",
      "Vin Diesel",
      "Bradley Cooper",
      "Sean Gunn",
      "Chukwudi Iwuji",
      "Will Poulter",
      "Maria Bakalova",
      "Sylvester Stallone",
    ],
    rating: 3.7,
  },

  {
    id: "6",
    title: "Bird Box Barcelona",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hOb6ODI7QQFKkOe3eJU2Fdh2fk1.jpg",
    category: ["Thriller", "Drama", "Science Fiction", "Horror"],
    duration: { hr: 2, min: 4 },
    date: "07/14/2023",
    description:
      "After a mysterious force decimates the world's population, Sebastian must navigate his own survival journey through the desolate streets of Barcelona. As he forms uneasy alliances with other survivors and they try to escape the city, an unexpected and even more sinister threat grows.",
    trailer: "zdDN_mflfSY",
    cast: [
      "Mario Casas",
      "Georgina Campbell",
      "Diego Calva",
      "Naila Schuberth",
      "Alejandra Howard",
      "Patrick Criado",
      "Celia Freijeiro",
      "Lola Dueñas",
    ],
    rating: 3.4,
  },

  {
    id: "7",
    title: "Barbie",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/Chuuh24JEqkYtgjq7fNfNDUnup.jpg",
    category: ["Comedy", "Adventure", "Fantasy"],
    duration: { hr: 1, min: 54 },
    date: "07/21/2023",
    description:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    trailer: "pBk4NYhWNMM",
    cast: [
      "Margot Robbie",
      "Ryan Gosling",
      "America Ferrera",
      "Ariana Greenblatt",
      "Kate McKinnon",
      "Michael Cera",
      "Simu Liu",
      "Issa Rae",
      "Kingsley Ben-Adir",
    ],
    rating: 4.4,
  },

  {
    id: "8",
    title: "Fast X",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    category: ["Action", "Crime", "Thriller"],
    duration: { hr: 2, min: 22 },
    date: "05/19/2023",
    description:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    trailer: "eoOaKN4qCKw",
    cast: [
      "Vin Diesel",
      "Michelle Rodriguez",
      "Tyrese Gibson",
      "Ludacris",
      "John Cena",
      "Jason Momoa",
      "Nathalie Emmanuel",
      "Jordana Brewster",
      "Sung Kang",
      "Alan Ritchson",
      "Brie Larson",
      "Jason Statham",
      "Dwayne Johnson",
      "Gal Gadot",
    ],
    rating: 4.1,
  },

  {
    id: "9",
    title: "John Wick: Chapter 4",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vppo7eOOkkjoSoBSglYIxLDB0dJ.jpg",
    category: ["Action", "Thriller", "Crime"],
    duration: { hr: 2, min: 50 },
    date: "03/24/2023",
    description:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    trailer: "yjRHZEUamCc",
    cast: [
      "Keanu Reeves",
      "Donnie Yen",
      "Bill Skarsgård",
      "Ian McShane",
      "Laurence Fishburne",
      "Lance Reddick",
      "Clancy Brown",
      "Hiroyuki Sanada",
      "Rina Sawayama",
      "Natalia Tena",
    ],
    rating: 4.6,
  },

  {
    id: "10",
    title: "Secret Invasion",
    poster:
      "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f5ZMzzCvt2IzVDxr54gHPv9jlC9.jpg",
    category: ["Drama", "Sci-Fi", "Fantasy", "Action", "Adventure"],
    duration: { hr: 3, min: 39 },
    date: "06/21/2023",
    description:
      "Secret Invasion Season 1 Consists 5 Episodes (Episode running time: 35-55 Minutes). Nick Fury learns of a secret invasion of Earth by a faction of shapeshifting Skrulls; Fury joins his allies, and together they race against time to thwart an imminent Skrull invasion and save humanity. Nick Fury and Talos discover a faction of shapeshifting Skrulls who have been infiltrating Earth for years.",
    trailer: "Tp_YZNqNBhw",
    cast: [
      "Samuel L. Jackson",
      "Ben Mendelsohn",
      "Kingsley Ben-Adir",
      "Killian Scott",
      "Samuel Adewunmi",
      "Dermot Mulroney",
      "Emilia Clarke",
      "Olivia Colman",
      "Don Cheadle",
    ],
    rating: 4.1,
  },
];

export const CATEGORIES = [
  "Romance",
  "Comedy",
  "Fictional",
  "Science",
  "History",
  "Documentary",
  "Science Fiction (Sci-Fi)",
  "Mystery",
  "Horror",
  "Crime",
  "Art Film",
  "Short Film",
  "Anthology",
  "Fantasy",
  "Musical",
  "TV Series",
  "Web Series",
  "Fairy Tale",
  "Thriller",
  "Drama",
  "Sports",
  "Action",
  "Adventure",
  "Animation",
  "Anime",
  "Devotional",
  "Patroitic",
  "BollyWood",
  "HollyWood",
  "Western",
  "Educational",
  "Adult",
  "Reality",
  "Talk Show",
  "Political",
  "Religious",
  "Stand-Up Comedy",
];

export const mood = {
  angry: "/Img/Angry.gif",
  happy: "/Img/Smiling.gif",
  sad: "/Img/Sad.gif",
  surprised: "/Img/Surprise.gif",
};
